module.exports = [
  {
    division: "ocd-division/country:us/state:ks",
    office: "United States Senate",
    name: "To Be Determined",
    sortOrder: 11,
  },
  {
    division: "ocd-division/country:us/state:ks/cd:1",
    office: "United States House of Representatives District 1",
    name: "No Endorsement",
    sortOrder: 21,
  },
  {
    division: "ocd-division/country:us/state:ks/cd:2",
    office: "United States House of Representatives District 2",
    name: "Patrick Schmidt",
    sortOrder: 21,
  },
  {
    division: "ocd-division/country:us/state:ks/cd:3",
    office: "United States House of Representatives District 3",
    name: "Sharice Davids",
    sortOrder: 21,
  },
  {
    division: "ocd-division/country:us/state:ks/cd:4",
    office: "United States House of Representatives District 4",
    name: "Bob Hernandez",
    sortOrder: 21,
  },
  {
    division: "ocd-division/country:us/state:ks",
    office: "Kansas Governor",
    name: "Laura Kelly/David Toland",
    sortOrder: 31,
  },
  {
    division: "ocd-division/country:us/state:ks",
    office: "Kansas Secretary of State",
    name: "Jeanna Repass",
    sortOrder: 32,
  },
  {
    division: "ocd-division/country:us/state:ks",
    office: "Kansas Attorney General",
    name: "Chris Mann",
    sortOrder: 33,
  },
  {
    division: "ocd-division/country:us/state:ks",
    office: "Kansas State Treasurer",
    name: "Lynn Rogers",
    sortOrder: 34,
  },
  {
    division: "ocd-division/country:us/state:ks",
    office: "Kansas Commissioner of Insurance",
    name: "Vicki Schmidt",
    sortOrder: 35,
  },
  {
    division: "ocd-division/country:us/state:ks/sldu:38",
    office: "Kansas Senate District 38",
    name: "Jose Lara",
    sortOrder: 41,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:1",
    office: "Kansas House District 1",
    name: "Paul D. Rogers",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:2",
    office: "Kansas House District 2",
    name: "No Endorsement",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:3",
    office: "Kansas House District 3",
    name: "No Endorsement",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:4",
    office: "Kansas House District 4",
    name: "No Endorsement",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:5",
    office: "Kansas House District 5",
    name: "Carrie Barth",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:6",
    office: "Kansas House District 6",
    name: "Nina Fricke",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:7",
    office: "Kansas House District 7",
    name: "No Endorsement",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:8",
    office: "Kansas House District 8",
    name: "To Be Determined",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:9",
    office: "Kansas House District 9",
    name: "Alana Cloutier",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:10",
    office: "Kansas House District 10",
    name: "Christina Haswood",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:11",
    office: "Kansas House District 11",
    name: "Gregory L. Wilkinson",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:12",
    office: "Kansas House District 12",
    name: "No Endorsement",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:13",
    office: "Kansas House District 13",
    name: "No Endorsement",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:14",
    office: "Kansas House District 14",
    name: "To Be Determined",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:15",
    office: "Kansas House District 15",
    name: "To Be Determined",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:16",
    office: "Kansas House District 16",
    name: "Linda Featherston",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:17",
    office: "Kansas House District 17",
    name: "Jo Ella Hoye",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:18",
    office: "Kansas House District 18",
    name: "Cindy Neighbor",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:19",
    office: "Kansas House District 19",
    name: "Stephanie Sawyer Clayton",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:20",
    office: "Kansas House District 20",
    name: "Mari-Lynn Poskin",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:21",
    office: "Kansas House District 21",
    name: "Jerry Stogsdill",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:22",
    office: "Kansas House District 22",
    name: "Lindsay Vaughn",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:23",
    office: "Kansas House District 23",
    name: "Susan Ruiz",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:24",
    office: "Kansas House District 24",
    name: "Jarrod Ousley",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:25",
    office: "Kansas House District 25",
    name: "Rui Xu",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:26",
    office: "Kansas House District 26",
    name: "To Be Determined",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:27",
    office: "Kansas House District 27",
    name: "Christi Pribula",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:28",
    office: "Kansas House District 28",
    name: "To Be Determined",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:29",
    office: "Kansas House District 29",
    name: "Heather Meyer",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:30",
    office: "Kansas House District 30",
    name: "Courtney Eiterich",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:31",
    office: "Kansas House District 31",
    name: "Louis E. Ruiz",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:32",
    office: "Kansas House District 32",
    name: "Pam Curtis",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:33",
    office: "Kansas House District 33",
    name: "Bill Hutton",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:34",
    office: "Kansas House District 34",
    name: "Valdenia C. Winn",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:35",
    office: "Kansas House District 35",
    name: "Marvin S.Robinson II",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:36",
    office: "Kansas House District 36",
    name: "Lynn Melton",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:37",
    office: "Kansas House District 37",
    name: "Melissa Oropeza",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:38",
    office: "Kansas House District 38",
    name: "No Endorsement",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:39",
    office: "Kansas House District 39",
    name: "To Be Determined",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:40",
    office: "Kansas House District 40",
    name: "To Be Determined",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:41",
    office: "Kansas House District 41",
    name: "To Be Determined",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:42",
    office: "Kansas House District 42",
    name: "No Endorsement",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:43",
    office: "Kansas House District 43",
    name: "Keith Davenport",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:44",
    office: "Kansas House District 44",
    name: "Barbara W. Ballard",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:45",
    office: "Kansas House District 45",
    name: "Mike Amyx",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:46",
    office: "Kansas House District 46",
    name: "Dennis “Boog” Highberger",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:47",
    office: "Kansas House District 47",
    name: "No Endorsement",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:48",
    office: "Kansas House District 48",
    name: "Dan Osman",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:49",
    office: "Kansas House District 49",
    name: "To Be Determined",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:50",
    office: "Kansas House District 50",
    name: "No Endorsement",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:51",
    office: "Kansas House District 51",
    name: "Kenny Titus",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:52",
    office: "Kansas House District 52",
    name: "To Be Determined",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:53",
    office: "Kansas House District 53",
    name: "To Be Determined",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:54",
    office: "Kansas House District 54",
    name: "Lyndon Johnson",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:55",
    office: "Kansas House District 55",
    name: "To Be Determined",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:56",
    office: "Kansas House District 56",
    name: "Virgil Weigel",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:57",
    office: "Kansas House District 57",
    name: "John Alcala",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:58",
    office: "Kansas House District 58",
    name: "Vic Miller",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:59",
    office: "Kansas House District 59",
    name: "No Endorsement",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:60",
    office: "Kansas House District 60",
    name: "Mic McGuire",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:61",
    office: "Kansas House District 61",
    name: "No Endorsement",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:62",
    office: "Kansas House District 62",
    name: "No Endorsement",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:63",
    office: "Kansas House District 63",
    name: "No Endorsement",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:64",
    office: "Kansas House District 64",
    name: "Patricia Smetana",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:65",
    office: "Kansas House District 65",
    name: "NO Endorsement",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:66",
    office: "Kansas House District 66",
    name: "Sydney Carlin",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:67",
    office: "Kansas House District 67",
    name: "Kim Zito",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:68",
    office: "Kansas House District 68",
    name: "Michael Seymour II",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:69",
    office: "Kansas House District 69",
    name: "Molly Molina",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:70",
    office: "Kansas House District 70",
    name: "No Endorsement",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:71",
    office: "Kansas House District 71",
    name: "No Endorsement",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:72",
    office: "Kansas House District 72",
    name: "No Endorsement",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:73",
    office: "Kansas House District 73",
    name: "No Endorsement",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:74",
    office: "Kansas House District 74",
    name: "No Endorsement",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:75",
    office: "Kansas House District 75",
    name: "No Endorsement",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:76",
    office: "Kansas House District 76",
    name: "Chuck Tores",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:77",
    office: "Kansas House District 77",
    name: "No Endorsement",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:78",
    office: "Kansas House District 78",
    name: "To Be Determined",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:79",
    office: "Kansas House District 79",
    name: "Kris Trimmer",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:80",
    office: "Kansas House District 80",
    name: "No Endorsement",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:81",
    office: "Kansas House District 81",
    name: "No Endorsement",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:82",
    office: "Kansas House District 82",
    name: "Misti Hobbs",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:83",
    office: "Kansas House District 83",
    name: "Henry Helgerson",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:84",
    office: "Kansas House District 84",
    name: "Ford Carr",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:85",
    office: "Kansas House District 85",
    name: "Jalon Britton",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:86",
    office: "Kansas House District 86",
    name: "No Endorsement",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:87",
    office: "Kansas House District 87",
    name: "Chris Strong",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:88",
    office: "Kansas House District 88",
    name: "Chick Schmidt",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:89",
    office: "Kansas House District 89",
    name: "KC Ohaebosim",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:90",
    office: "Kansas House District 90",
    name: "No Endorsement",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:91",
    office: "Kansas House District 91",
    name: "Brooke Chong",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:92",
    office: "Kansas House District 92",
    name: "John Carmichael",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:93",
    office: "Kansas House District 93",
    name: "No Endorsement",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:94",
    office: "Kansas House District 94",
    name: "Robert Howes",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:95",
    office: "Kansas House District 95",
    name: "Tom Sawyer",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:96",
    office: "Kansas House District 96",
    name: "No Endorsement",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:97",
    office: "Kansas House District 97",
    name: "No Endorsement",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:98",
    office: "Kansas House District 98",
    name: "No Endorsement",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:99",
    office: "Kansas House District 99",
    name: "No Endorsement",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:100",
    office: "Kansas House District 100",
    name: "Mike McCorkle",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:101",
    office: "Kansas House District 101",
    name: "No Endorsement",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:102",
    office: "Kansas House District 102",
    name: "Jason Probst",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:103",
    office: "Kansas House District 103",
    name: "Angela Martinez",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:104",
    office: "Kansas House District 104",
    name: "Garth Strand",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:105",
    office: "Kansas House District 105",
    name: "Jaelynn Elise Abegg",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:106",
    office: "Kansas House District 106",
    name: "NO Endorsement",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:107",
    office: "Kansas House District 107",
    name: "No Endorsement",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:108",
    office: "Kansas House District 108",
    name: "Brandon Woodard",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:109",
    office: "Kansas House District 109",
    name: "No Endorsement",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:110",
    office: "Kansas House District 110",
    name: "No Endorsement",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:111",
    office: "Kansas House District 111",
    name: "Edward H. Hammond",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:112",
    office: "Kansas House District 112",
    name: "No Endorsement",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:113",
    office: "Kansas House District 113",
    name: "No Endorsement",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:114",
    office: "Kansas House District 114",
    name: "No Endorsement",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:115",
    office: "Kansas House District 115",
    name: "No Endorsement",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:116",
    office: "Kansas House District 116",
    name: "Kristen Lee Barger",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:117",
    office: "Kansas House District 117",
    name: "Courtney Tripp",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:118",
    office: "Kansas House District 118",
    name: "No Endorsement",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:119",
    office: "Kansas House District 119",
    name: "No Endorsement",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:120",
    office: "Kansas House District 120",
    name: "No Endorsement",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:121",
    office: "Kansas House District 121",
    name: "To Be Determined",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:122",
    office: "Kansas House District 122",
    name: "No endorsement",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:123",
    office: "Kansas House District 123",
    name: "No Endorsement",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:124",
    office: "Kansas House District 124",
    name: "No Endorsement",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:125",
    office: "Kansas House District 125",
    name: "No Endorsement",
    sortOrder: 51,
  },
  {
    division:
      "ocd-division/country:us/state:ks/county:sedgwick/council_district:1",
    office: "Sedgwick County Commission District 1",
    name: "No Endorsement",
    sortOrder: 61,
  },
  {
    division:
      "ocd-division/country:us/state:ks/county:sedgwick/council_district:4",
    office: "Sedgwick County Commission District 4",
    name: "No Endorsement",
    sortOrder: 61,
  },
  {
    division:
      "ocd-division/country:us/state:ks/county:sedgwick/council_district:5",
    office: "Sedgwick County Commission District 5",
    name: "John McIntosh",
    sortOrder: 61,
  },

  {
    division: "ocd-division/country:us/state:ks/county:reno/council_district:1",
    office: "Reno County Commission District 1",
    name: "No Endorsement",
    sortOrder: 61,
  },
  {
    division: "ocd-division/country:us/state:ks/county:reno/council_district:4",
    office: "Reno County Commission District 4",
    name: "Michael Jobe",
    sortOrder: 61,
  },
  {
    division: "ocd-division/country:us/state:ks/county:reno/council_district:5",
    office: "Reno County Commission District 5",
    name: "Penelope Poitras",
    sortOrder: 61,
  },
];
