module.exports = [
  {
    division: "ocd-division/country:us/state:ks/sldl:103",
    office: "Kansas House District 103",
    name: "Angela Martinez",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:85",
    office: "Kansas House District 85",
    name: "Aonya Kendrick Barnett",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:98",
    office: "Kansas House District 98",
    name: "Carol Brewer",
    sortOrder: 51,
  },
  {
    division:
      "ocd-division/country:us/state:ks/county:sedgwick/council_district:3",
    office: "Sedgwick County Commission District 3",
    name: "Celeste Racette",
    sortOrder: 61,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:97",
    office: "Kansas House District 97",
    name: "Christine Pruitt",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:96",
    office: "Kansas House District 96",
    name: "Dan Johnson",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:77",
    office: "Kansas House District 77",
    name: "Doug Law",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/cd:4",
    office: "United States House of Representatives District 4",
    name: "Esau Freeman",
    sortOrder: 21,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:84",
    office: "Kansas House District 84",
    name: "Ford Carr",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:83",
    office: "Kansas House District 83",
    name: "Henry Helgerson",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldu:26",
    office: "Kansas House District 26",
    name: "J. C. Moore",
    sortOrder: 41,
  },
  {
    division: "ocd-division/country:us/state:ks/sldu:31",
    office: "Kansas House District 31",
    name: "Jason Miller",
    sortOrder: 41,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:102",
    office: "Kansas House District 102",
    name: "Jason Probst",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldu:27",
    office: "Kansas House District 27",
    name: "Jennifer Herington",
    sortOrder: 41,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:105",
    office: "Kansas House District 105",
    name: "John Burke",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:92",
    office: "Kansas House District 92",
    name: "John Carmichael",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:93",
    office: "Kansas House District 93",
    name: "Justin L. Shore",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:89",
    office: "Kansas House District 89",
    name: "KC Ohaebosim",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:91",
    office: "Kansas House District 91",
    name: "Keisha McClish Couts",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:82",
    office: "Kansas House District 82",
    name: "Kyle Beauchamp",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldu:32",
    office: "Kansas House District 32",
    name: "Lawrence Moreno",
    sortOrder: 41,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:104",
    office: "Kansas House District 104",
    name: "Lynnette Krieger-Zook",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldu:25",
    office: "Kansas House District 25",
    name: "Mary Ware",
    sortOrder: 41,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:100",
    office: "Kansas House District 100",
    name: "Mike McCorkle",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:87",
    office: "Kansas House District 87",
    name: "Mike Snider",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:12",
    office: "Kansas House District 12",
    name: "No endorsement",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:72",
    office: "Kansas House District 72",
    name: "No endorsement",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:74",
    office: "Kansas House District 74",
    name: "No endorsement",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:75",
    office: "Kansas House District 75",
    name: "No endorsement",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:79",
    office: "Kansas House District 79",
    name: "No endorsement",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:80",
    office: "Kansas House District 80",
    name: "No endorsement",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:81",
    office: "Kansas House District 81",
    name: "No endorsement",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:94",
    office: "Kansas House District 94",
    name: "No endorsement",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:99",
    office: "Kansas House District 99",
    name: "No Endorsement",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:101",
    office: "Kansas House District 101",
    name: "No endorsement",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:114",
    office: "Kansas House District 114",
    name: "No endorsement",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:116",
    office: "Kansas House District 116",
    name: "No endorsement",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldu:14",
    office: "Kansas House District 14",
    name: "No endorsement",
    sortOrder: 41,
  },
  {
    division: "ocd-division/country:us/state:ks/sldu:28",
    office: "Kansas House District 28",
    name: "No endorsement",
    sortOrder: 41,
  },
  {
    division: "ocd-division/country:us/state:ks/sldu:30",
    office: "Kansas House District 30",
    name: "No endorsement",
    sortOrder: 41,
  },
  {
    division: "ocd-division/country:us/state:ks/sldu:29",
    office: "Kansas House District 29",
    name: "Oletha Faust Goudeau",
    sortOrder: 41,
  },
  {
    division:
      "ocd-division/country:us/state:ks/county:sedgwick/council_district:2",
    office: "Sedgwick County Commission District 2",
    name: "Sarah Lopez",
    sortOrder: 61,
  },
  {
    division: "ocd-division/country:us/state:ks/sldu:16",
    office: "Kansas House District 16",
    name: "Sasha Islam",
    sortOrder: 41,
  },
  {
    division: "ocd-division/country:us/state:ks/sldu:34",
    office: "Kansas House District 34",
    name: "Shana Henry",
    sortOrder: 41,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:86",
    office: "Kansas House District 86",
    name: "Silas Miller",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:95",
    office: "Kansas House District 95",
    name: "Tom Sawyer",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:90",
    office: "Kansas House District 90",
    name: "Tracy Edingfield",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:88",
    office: "Kansas House District 88",
    name: "Winner of Democratic Primary",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:1",
    office: "Kansas House District 1",
    name: "...coming soon",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:2",
    office: "Kansas House District 2",
    name: "...coming soon",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:3",
    office: "Kansas House District 3",
    name: "...coming soon",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:4",
    office: "Kansas House District 4",
    name: "...coming soon",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:5",
    office: "Kansas House District 5",
    name: "...coming soon",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:6",
    office: "Kansas House District 6",
    name: "...coming soon",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:7",
    office: "Kansas House District 7",
    name: "...coming soon",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:8",
    office: "Kansas House District 8",
    name: "...coming soon",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:9",
    office: "Kansas House District 9",
    name: "...coming soon",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:10",
    office: "Kansas House District 10",
    name: "...coming soon",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:11",
    office: "Kansas House District 11",
    name: "...coming soon",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:13",
    office: "Kansas House District 13",
    name: "...coming soon",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:14",
    office: "Kansas House District 14",
    name: "...coming soon",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:15",
    office: "Kansas House District 15",
    name: "...coming soon",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:16",
    office: "Kansas House District 16",
    name: "...coming soon",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:17",
    office: "Kansas House District 17",
    name: "...coming soon",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:18",
    office: "Kansas House District 18",
    name: "...coming soon",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:19",
    office: "Kansas House District 19",
    name: "...coming soon",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:20",
    office: "Kansas House District 20",
    name: "...coming soon",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:21",
    office: "Kansas House District 21",
    name: "...coming soon",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:22",
    office: "Kansas House District 22",
    name: "...coming soon",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:23",
    office: "Kansas House District 23",
    name: "...coming soon",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:24",
    office: "Kansas House District 24",
    name: "...coming soon",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:25",
    office: "Kansas House District 25",
    name: "...coming soon",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:26",
    office: "Kansas House District 26",
    name: "...coming soon",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:27",
    office: "Kansas House District 27",
    name: "...coming soon",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:28",
    office: "Kansas House District 28",
    name: "...coming soon",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:29",
    office: "Kansas House District 29",
    name: "...coming soon",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:30",
    office: "Kansas House District 30",
    name: "...coming soon",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:31",
    office: "Kansas House District 31",
    name: "...coming soon",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:32",
    office: "Kansas House District 32",
    name: "...coming soon",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:33",
    office: "Kansas House District 33",
    name: "...coming soon",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:34",
    office: "Kansas House District 34",
    name: "...coming soon",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:35",
    office: "Kansas House District 35",
    name: "...coming soon",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:36",
    office: "Kansas House District 36",
    name: "...coming soon",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:37",
    office: "Kansas House District 37",
    name: "...coming soon",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:38",
    office: "Kansas House District 38",
    name: "...coming soon",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:39",
    office: "Kansas House District 39",
    name: "...coming soon",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:40",
    office: "Kansas House District 40",
    name: "...coming soon",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:41",
    office: "Kansas House District 41",
    name: "...coming soon",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:42",
    office: "Kansas House District 42",
    name: "...coming soon",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:43",
    office: "Kansas House District 43",
    name: "...coming soon",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:44",
    office: "Kansas House District 44",
    name: "...coming soon",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:45",
    office: "Kansas House District 45",
    name: "...coming soon",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:46",
    office: "Kansas House District 46",
    name: "...coming soon",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:47",
    office: "Kansas House District 47",
    name: "...coming soon",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:48",
    office: "Kansas House District 48",
    name: "...coming soon",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:49",
    office: "Kansas House District 49",
    name: "...coming soon",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:50",
    office: "Kansas House District 50",
    name: "...coming soon",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:51",
    office: "Kansas House District 51",
    name: "...coming soon",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:52",
    office: "Kansas House District 52",
    name: "...coming soon",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:53",
    office: "Kansas House District 53",
    name: "...coming soon",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:54",
    office: "Kansas House District 54",
    name: "...coming soon",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:55",
    office: "Kansas House District 55",
    name: "...coming soon",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:56",
    office: "Kansas House District 56",
    name: "...coming soon",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:57",
    office: "Kansas House District 57",
    name: "...coming soon",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:58",
    office: "Kansas House District 58",
    name: "...coming soon",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:59",
    office: "Kansas House District 59",
    name: "...coming soon",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:60",
    office: "Kansas House District 60",
    name: "...coming soon",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:61",
    office: "Kansas House District 61",
    name: "...coming soon",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:62",
    office: "Kansas House District 62",
    name: "...coming soon",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:63",
    office: "Kansas House District 63",
    name: "...coming soon",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:64",
    office: "Kansas House District 64",
    name: "...coming soon",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:65",
    office: "Kansas House District 65",
    name: "...coming soon",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:66",
    office: "Kansas House District 66",
    name: "...coming soon",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:67",
    office: "Kansas House District 67",
    name: "...coming soon",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:68",
    office: "Kansas House District 68",
    name: "...coming soon",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:69",
    office: "Kansas House District 69",
    name: "...coming soon",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:70",
    office: "Kansas House District 70",
    name: "...coming soon",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:71",
    office: "Kansas House District 71",
    name: "...coming soon",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:73",
    office: "Kansas House District 73",
    name: "...coming soon",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:76",
    office: "Kansas House District 76",
    name: "...coming soon",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:78",
    office: "Kansas House District 78",
    name: "...coming soon",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:106",
    office: "Kansas House District 106",
    name: "...coming soon",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:107",
    office: "Kansas House District 107",
    name: "...coming soon",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:108",
    office: "Kansas House District 108",
    name: "...coming soon",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:109",
    office: "Kansas House District 109",
    name: "...coming soon",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:110",
    office: "Kansas House District 110",
    name: "...coming soon",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:111",
    office: "Kansas House District 111",
    name: "...coming soon",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:112",
    office: "Kansas House District 112",
    name: "...coming soon",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:113",
    office: "Kansas House District 113",
    name: "...coming soon",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:115",
    office: "Kansas House District 115",
    name: "...coming soon",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:117",
    office: "Kansas House District 117",
    name: "...coming soon",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:118",
    office: "Kansas House District 118",
    name: "...coming soon",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:119",
    office: "Kansas House District 119",
    name: "...coming soon",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:120",
    office: "Kansas House District 120",
    name: "...coming soon",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:121",
    office: "Kansas House District 121",
    name: "...coming soon",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:122",
    office: "Kansas House District 122",
    name: "...coming soon",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:123",
    office: "Kansas House District 123",
    name: "...coming soon",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:124",
    office: "Kansas House District 124",
    name: "...coming soon",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldl:125",
    office: "Kansas House District 125",
    name: "...coming soon",
    sortOrder: 51,
  },
  {
    division: "ocd-division/country:us/state:ks/sldu:1",
    office: "Kansas House District 1",
    name: "...coming soon",
    sortOrder: 41,
  },
  {
    division: "ocd-division/country:us/state:ks/sldu:2",
    office: "Kansas House District 2",
    name: "...coming soon",
    sortOrder: 41,
  },
  {
    division: "ocd-division/country:us/state:ks/sldu:3",
    office: "Kansas House District 3",
    name: "...coming soon",
    sortOrder: 41,
  },
  {
    division: "ocd-division/country:us/state:ks/sldu:4",
    office: "Kansas House District 4",
    name: "...coming soon",
    sortOrder: 41,
  },
  {
    division: "ocd-division/country:us/state:ks/sldu:5",
    office: "Kansas House District 5",
    name: "...coming soon",
    sortOrder: 41,
  },
  {
    division: "ocd-division/country:us/state:ks/sldu:6",
    office: "Kansas House District 6",
    name: "...coming soon",
    sortOrder: 41,
  },
  {
    division: "ocd-division/country:us/state:ks/sldu:7",
    office: "Kansas House District 7",
    name: "...coming soon",
    sortOrder: 41,
  },
  {
    division: "ocd-division/country:us/state:ks/sldu:8",
    office: "Kansas House District 8",
    name: "...coming soon",
    sortOrder: 41,
  },
  {
    division: "ocd-division/country:us/state:ks/sldu:9",
    office: "Kansas House District 9",
    name: "...coming soon",
    sortOrder: 41,
  },
  {
    division: "ocd-division/country:us/state:ks/sldu:10",
    office: "Kansas House District 10",
    name: "...coming soon",
    sortOrder: 41,
  },
  {
    division: "ocd-division/country:us/state:ks/sldu:11",
    office: "Kansas House District 11",
    name: "...coming soon",
    sortOrder: 41,
  },
  {
    division: "ocd-division/country:us/state:ks/sldu:12",
    office: "Kansas House District 12",
    name: "...coming soon",
    sortOrder: 41,
  },
  {
    division: "ocd-division/country:us/state:ks/sldu:13",
    office: "Kansas House District 13",
    name: "...coming soon",
    sortOrder: 41,
  },
  {
    division: "ocd-division/country:us/state:ks/sldu:15",
    office: "Kansas House District 15",
    name: "...coming soon",
    sortOrder: 41,
  },
  {
    division: "ocd-division/country:us/state:ks/sldu:17",
    office: "Kansas House District 17",
    name: "...coming soon",
    sortOrder: 41,
  },
  {
    division: "ocd-division/country:us/state:ks/sldu:18",
    office: "Kansas House District 18",
    name: "...coming soon",
    sortOrder: 41,
  },
  {
    division: "ocd-division/country:us/state:ks/sldu:19",
    office: "Kansas House District 19",
    name: "...coming soon",
    sortOrder: 41,
  },
  {
    division: "ocd-division/country:us/state:ks/sldu:20",
    office: "Kansas House District 20",
    name: "...coming soon",
    sortOrder: 41,
  },
  {
    division: "ocd-division/country:us/state:ks/sldu:21",
    office: "Kansas House District 21",
    name: "...coming soon",
    sortOrder: 41,
  },
  {
    division: "ocd-division/country:us/state:ks/sldu:22",
    office: "Kansas House District 22",
    name: "...coming soon",
    sortOrder: 41,
  },
  {
    division: "ocd-division/country:us/state:ks/sldu:23",
    office: "Kansas House District 23",
    name: "...coming soon",
    sortOrder: 41,
  },
  {
    division: "ocd-division/country:us/state:ks/sldu:24",
    office: "Kansas House District 24",
    name: "...coming soon",
    sortOrder: 41,
  },
  {
    division: "ocd-division/country:us/state:ks/sldu:33",
    office: "Kansas House District 33",
    name: "...coming soon",
    sortOrder: 41,
  },
  {
    division: "ocd-division/country:us/state:ks/sldu:35",
    office: "Kansas House District 35",
    name: "...coming soon",
    sortOrder: 41,
  },
  {
    division: "ocd-division/country:us/state:ks/sldu:36",
    office: "Kansas House District 36",
    name: "...coming soon",
    sortOrder: 41,
  },
  {
    division: "ocd-division/country:us/state:ks/sldu:37",
    office: "Kansas House District 37",
    name: "...coming soon",
    sortOrder: 41,
  },
  {
    division: "ocd-division/country:us/state:ks/sldu:38",
    office: "Kansas House District 38",
    name: "...coming soon",
    sortOrder: 41,
  },
  {
    division: "ocd-division/country:us/state:ks/sldu:39",
    office: "Kansas House District 39",
    name: "...coming soon",
    sortOrder: 41,
  },
  {
    division: "ocd-division/country:us/state:ks/sldu:40",
    office: "Kansas House District 40",
    name: "...coming soon",
    sortOrder: 41,
  },
  {
    division: "ocd-division/country:us/state:ks/cd:1",
    office: "United States House of Representatives District 1",
    name: "...coming soon",
    sortOrder: 21,
  },
  {
    division: "ocd-division/country:us/state:ks/cd:2",
    office: "United States House of Representatives District 2",
    name: "...coming soon",
    sortOrder: 21,
  },
  {
    division: "ocd-division/country:us/state:ks/cd:3",
    office: "United States House of Representatives District 3",
    name: "...coming soon",
    sortOrder: 21,
  },
  {
    division: "ocd-division/country:us/state:ks",
    office: "United States President",
    name: "Kamala Harris",
    sortOrder: 1,
  },
];
